FROM postgres:9.4

RUN apt-get update && apt-get install --fix-missing -y \
  build-essential \
  libpq-dev \
  libgeos-dev \
  libgmp3-dev \
  libproj-dev \
  postgresql-contrib \
  postgis \
  postgresql-9.4-postgis-2.1 \
  postgresql-9.4-postgis-2.1-scripts \
  postgresql-9.4-postgis-scripts
