FROM debian:sid

RUN \
  apt-get update && \
  apt-get install --fix-missing -y openjdk-8-jdk wget maven git

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64

RUN \
  git clone https://github.com/pjsier/OpenTripPlanner.git && mv OpenTripPlanner /var/otp

WORKDIR /var/otp

RUN git checkout -b graph-updater-311 && git pull origin graph-updater-311
RUN mvn package && mv /var/otp/target/otp-0.20.0-SNAPSHOT-shaded.jar /var/otp/otp.jar

ENV OTP_BASE /var/otp
ENV OTP_GRAPHS /var/otp/graphs

RUN \
  mkdir -p /var/otp/graphs/chicago && \
  wget -P /var/otp/graphs/chicago http://www.transitchicago.com/downloads/sch_data/google_transit.zip && \
  wget -P /var/otp/graphs/chicago https://s3.amazonaws.com/metro-extracts.mapzen.com/chicago_illinois.osm.pbf && \
  java -Xmx8G -jar /var/otp/otp.jar --build /var/otp/graphs

EXPOSE 8080
EXPOSE 8081

ENTRYPOINT [ "java", "-Xmx6G", "-Xverify:none", "-jar", "/var/otp/otp.jar" ]

CMD [ "--help" ]
