#!/bin/bash
export AWS_ACCESS_KEY_ID=XXXX
export AWS_SECRET_ACCESS_KEY=XXXX
export CHI_311_KEY=XXXX
export TEST_311_KEY=XXXX
export S3_REGION=XXXX
export SECRET_KEY_BASE=XXXX
export SECRET_TOKEN=XXXX
